### ISSUE TITLE
Help text can be shown exactly once

### ISSUE THREAD

**Issue by xxxserxxx** [spezifisch/stmps#8]
See https://github.com/rivo/tview/issues/986 for grubby details, analysis and resolution.

TL;DR is that the `helpWidget`'s input capture function was _always_ being called after the first display. Since the function always closed the window on input, this resulted in the window being opened and immediately being closed. I'm submitting a PR that addressed this shortly.

**Comment by xxxserxxx** [comment]
This should be fixed by PR #9 . Github isn't showing a reference, for me, at least.

**Comment by ptrcnull** [comment]
> Github isn't showing a reference, for me, at least.

fwiw, it's kind of a funny bug - because of how GitHub handles forks ( every forked repo is actually a separate *thing* (namespace, i guess?) in the main repo ), your `#8` got converted into a reference to `https://github.com/wildeyedskies/stmp/pull/8` before GitHub could match which fork you're contributing to
